#!/usr/bin/env bash
# Add 127.0.0.2 hostname to /etc/hosts
sudo sed '/127\.0\.0\.1[[:space:]]\+localhost/d' /etc/hosts | sudo tee /etc/hosts.tmp > /dev/null
echo "127.0.0.2	localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
